// examples/react/src/App.tsx
import { A11yHud } from "@a11y-hud/react";
import { useRef, useState } from "react";
import { Link, Route, BrowserRouter as Router, Routes } from "react-router-dom";
import { PageA } from "./pages/PageA.js";
import { PageB } from "./pages/PageB.js";

export function App() {
  const [scopeEnabled, setScopeEnabled] = useState(false);
  const [extraTabindex, setExtraTabindex] = useState(false);
  const scopeSectionRef = useRef<HTMLDivElement>(null);

  return (
    <Router>
      <A11yHud scope={scopeEnabled ? scopeSectionRef : undefined} />

      <nav>
        <Link to="/">Page A</Link>
        <Link to="/page-b">Page B</Link>
      </nav>

      <div className="controls">
        <button type="button" id="btn-toggle-scope" onClick={() => setScopeEnabled((s) => !s)}>
          {scopeEnabled ? "Disable scope" : "Enable scope"}
        </button>
        <button type="button" id="btn-add-violation" onClick={() => setExtraTabindex(true)}>
          Add violation
        </button>
      </div>

      {extraTabindex && (
        <button
          type="button"
          tabIndex={5}
          style={{ opacity: 0, position: "absolute", pointerEvents: "none" }}
        >
          Positive tabindex
        </button>
      )}

      {/* This unlabelled input is outside the scope section.
          It creates a `label` violation that disappears when scope is enabled. */}
      <input type="text" placeholder="Search (no label)" />

      <div ref={scopeSectionRef}>
        <Routes>
          <Route path="/" element={<PageA />} />
          <Route path="/page-b" element={<PageB />} />
        </Routes>
      </div>
    </Router>
  );
}

// examples/solid/src/App.tsx
import { A11yHud } from "@a11y-hud/solid";
import { Route, Router } from "@solidjs/router";
import { createSignal } from "solid-js";
import PageA from "./pages/PageA.tsx";
import PageB from "./pages/PageB.tsx";

export default function App() {
  const [scopeEnabled, setScopeEnabled] = createSignal(false);
  const [scopeSection, setScopeSection] = createSignal<HTMLDivElement | null>(null);
  const [extraTabindex, setExtraTabindex] = createSignal(false);

  return (
    <>
      <A11yHud scope={scopeEnabled() ? scopeSection() : undefined} />

      <nav>
        <a href="/">Page A</a>
        <a href="/page-b">Page B</a>
      </nav>

      <div class="controls">
        <button
          id="btn-toggle-scope"
          type="button"
          onClick={() => setScopeEnabled(!scopeEnabled())}
        >
          {scopeEnabled() ? "Disable scope" : "Enable scope"}
        </button>
        <button id="btn-add-violation" type="button" onClick={() => setExtraTabindex(true)}>
          Add violation
        </button>
      </div>

      {extraTabindex() && (
        <button
          type="button"
          tabIndex={5}
          style="opacity: 0; position: absolute; pointer-events: none"
        >
          Positive tabindex
        </button>
      )}

      <input type="text" placeholder="Search (no label)" />

      <div ref={setScopeSection}>
        <Router>
          <Route path="/" component={PageA} />
          <Route path="/page-b" component={PageB} />
        </Router>
      </div>
    </>
  );
}
