// packages/solid/src/hook.ts
import type { A11yHudElement, A11yHudInstance, AxeResults, Theme } from "a11y-hud";
import { mount } from "a11y-hud";
import { createEffect, onCleanup, onMount } from "solid-js";
import type { CreateA11yHudOptions, CreateA11yHudReturn } from "./types.js";

export function createA11yHud(options: CreateA11yHudOptions = {}): CreateA11yHudReturn {
  let instanceRef: A11yHudInstance | null = null;
  let elementRef: A11yHudElement | null = null;

  onMount(() => {
    const { theme, autoScan, debounce, runOnly } = options;
    const instance = mount({
      ...(theme !== undefined && { theme }),
      ...(autoScan !== undefined && { autoScan }),
      ...(debounce !== undefined && { debounce }),
      ...(runOnly !== undefined && { runOnly }),
    });
    instanceRef = instance;
    elementRef = document.querySelector<A11yHudElement>("a11y-hud");
    // NOTE: Do NOT run scan here — the scope effect (below) runs after onMount
    // and handles the initial scan.
  });

  onCleanup(() => {
    instanceRef?.unmount();
    instanceRef = null;
    elementRef = null;
  });

  // Render-settled: scope sync + rescan after prop changes.
  // Runs after onMount (registration order). On initial render: does the first scan.
  // On scope change (if options.scope is a reactive getter): rescans.
  createEffect(() => {
    if (!instanceRef || !elementRef) return;
    const el = elementRef;
    el.scopeElement = options.scope ?? undefined; // reactive read
    void instanceRef.runScan();
  });

  // Theme sync
  createEffect(() => {
    if (!instanceRef) return;
    const theme = options.theme; // reactive read
    if (theme !== undefined) instanceRef.setTheme(theme);
  });

  // autoScan sync
  createEffect(() => {
    const el = elementRef;
    if (!el) return;
    const autoScan = options.autoScan; // reactive read
    if (autoScan === false) {
      el.removeAttribute("auto-scan");
    } else {
      el.setAttribute("auto-scan", "");
    }
  });

  // debounce sync
  createEffect(() => {
    const el = elementRef;
    if (!el) return;
    const debounce = options.debounce; // reactive read
    if (debounce === undefined) return;
    el.setAttribute("debounce", String(debounce));
  });

  // runOnly sync
  createEffect(() => {
    if (!instanceRef) return;
    const runOnly = options.runOnly; // reactive read
    if (runOnly !== undefined) instanceRef.setRunOnly(runOnly);
  });

  function runScan(): Promise<AxeResults> {
    return instanceRef?.runScan() ?? Promise.resolve(null as unknown as AxeResults);
  }

  function setTheme(t: Theme): void {
    instanceRef?.setTheme(t);
  }

  function setRunOnly(tags: string[]): void {
    instanceRef?.setRunOnly(tags);
  }

  function exportResults(): string | null {
    return instanceRef?.exportResults() ?? null;
  }

  const ignores = {
    add(ruleId: string, selector?: string): void {
      instanceRef?.ignores.add(ruleId, selector);
    },
    remove(ruleId: string, selector?: string): void {
      instanceRef?.ignores.remove(ruleId, selector);
    },
    clear(): void {
      instanceRef?.ignores.clear();
    },
    list() {
      return instanceRef?.ignores.list() ?? [];
    },
    exportJson(): string {
      return instanceRef?.ignores.exportJson() ?? "[]";
    },
    importJson(json: string): void {
      instanceRef?.ignores.importJson(json);
    },
  };

  return { runScan, setTheme, setRunOnly, exportResults, ignores };
}

// packages/react/src/hook.ts
import type { A11yHudElement, A11yHudInstance, AxeResults, Theme } from "a11y-hud";
import { mount } from "a11y-hud";
import { useCallback, useEffect, useMemo, useRef } from "react";
import type { UseA11yHudOptions, UseA11yHudReturn } from "./types.js";

export function useA11yHud(options: UseA11yHudOptions = {}): UseA11yHudReturn {
  const { theme, scope, autoScan, debounce, runOnly } = options;
  const instanceRef = useRef<A11yHudInstance | null>(null);
  const elementRef = useRef<A11yHudElement | null>(null);

  // Mount the CE once. Capture the element reference immediately after mount()
  // so subsequent effects can access it without re-querying the DOM.
  // biome-ignore lint/correctness/useExhaustiveDependencies: intentional mount-once effect; initial options are applied here, changes are tracked by the separate sync effects below
  useEffect(() => {
    // exactOptionalPropertyTypes forbids passing `undefined` for optional props;
    // build the options object conditionally to satisfy the constraint.
    const instance = mount({
      ...(theme !== undefined && { theme }),
      ...(autoScan !== undefined && { autoScan }),
      ...(debounce !== undefined && { debounce }),
      ...(runOnly !== undefined && { runOnly }),
    });
    instanceRef.current = instance;
    elementRef.current = document.querySelector<A11yHudElement>("a11y-hud");
    return () => {
      instance.unmount();
      instanceRef.current = null;
      elementRef.current = null;
    };
  }, []);

  useEffect(() => {
    if (theme !== undefined) instanceRef.current?.setTheme(theme);
  }, [theme]);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (autoScan === false) {
      el.removeAttribute("auto-scan");
    } else {
      el.setAttribute("auto-scan", "");
    }
  }, [autoScan]);

  useEffect(() => {
    const el = elementRef.current;
    if (!el || debounce === undefined) return;
    el.setAttribute("debounce", String(debounce));
  }, [debounce]);

  useEffect(() => {
    if (runOnly !== undefined) instanceRef.current?.setRunOnly(runOnly);
  }, [runOnly]);

  // Render-settled signal: runs after every React commit. Always syncs scope
  // (including clearing it when scope becomes undefined), then triggers a
  // rescan. This is the adapter's core value — rescans fire after React
  // finishes rendering, catching route changes and prop-driven ARIA mutations
  // that the MutationObserver may coalesce.
  useEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;
    const el = elementRef.current;
    if (el) {
      el.scopeElement = scope?.current ?? undefined;
    }
    void instance.runScan();
  });

  const runScan = useCallback(
    (): Promise<AxeResults> =>
      instanceRef.current?.runScan() ?? Promise.resolve(null as unknown as AxeResults),
    []
  );

  const setTheme = useCallback((t: Theme): void => {
    instanceRef.current?.setTheme(t);
  }, []);

  const setRunOnly = useCallback((tags: string[]): void => {
    instanceRef.current?.setRunOnly(tags);
  }, []);

  const exportResults = useCallback((): string | null => {
    return instanceRef.current?.exportResults() ?? null;
  }, []);

  const ignores = useMemo(
    () => ({
      add(ruleId: string, selector?: string): void {
        instanceRef.current?.ignores.add(ruleId, selector);
      },
      remove(ruleId: string, selector?: string): void {
        instanceRef.current?.ignores.remove(ruleId, selector);
      },
      clear(): void {
        instanceRef.current?.ignores.clear();
      },
      list() {
        return instanceRef.current?.ignores.list() ?? [];
      },
      exportJson(): string {
        return instanceRef.current?.ignores.exportJson() ?? "[]";
      },
      importJson(json: string): void {
        instanceRef.current?.ignores.importJson(json);
      },
    }),
    []
  );

  return { runScan, setTheme, setRunOnly, exportResults, ignores };
}
